export const JoystickType = {
  SDL_JOYSTICK_TYPE_UNKNOWN: 0,
  SDL_JOYSTICK_TYPE_GAMEPAD: 1,
  SDL_JOYSTICK_TYPE_WHEEL: 2,
  SDL_JOYSTICK_TYPE_ARCADE_STICK: 3,
  SDL_JOYSTICK_TYPE_FLIGHT_STICK: 4,
  SDL_JOYSTICK_TYPE_DANCE_PAD: 5,
  SDL_JOYSTICK_TYPE_GUITAR: 6,
  SDL_JOYSTICK_TYPE_DRUM_KIT: 7,
  SDL_JOYSTICK_TYPE_ARCADE_PAD: 8,
  SDL_JOYSTICK_TYPE_THROTTLE: 9,
  SDL_JOYSTICK_TYPE_COUNT: 10,
} as const;

export type JoystickType = (typeof JoystickType)[keyof typeof JoystickType];
