export const GPUShaderFormat = {
  SDL_GPU_SHADERFORMAT_INVALID: 0,
  SDL_GPU_SHADERFORMAT_PRIVATE:
    (1 << 0) >>> 0 /**< Shaders for NDA'd platforms. */,
  SDL_GPU_SHADERFORMAT_SPIRV: (1 << 1) >>> 0 /**< SPIR-V shaders for Vulkan. */,
  SDL_GPU_SHADERFORMAT_DXBC:
    (1 << 2) >>> 0 /**< DXBC SM5_1 shaders for D3D12. */,
  SDL_GPU_SHADERFORMAT_DXIL:
    (1 << 3) >>> 0 /**< DXIL SM6_0 shaders for D3D12. */,
  SDL_GPU_SHADERFORMAT_MSL: (1 << 4) >>> 0 /**< MSL shaders for Metal. */,
  SDL_GPU_SHADERFORMAT_METALLIB:
    (1 << 5) >>> 0 /**< Precompiled metallib shaders for Metal. */,
} as const;

export type GPUShaderFormat =
  (typeof GPUShaderFormat)[keyof typeof GPUShaderFormat];

export const GPUTextureFormat = {
  SDL_GPU_TEXTUREFORMAT_INVALID: 0,

  /* Unsigned Normalized Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_A8_UNORM: 1,
  SDL_GPU_TEXTUREFORMAT_R8_UNORM: 2,
  SDL_GPU_TEXTUREFORMAT_R8G8_UNORM: 3,
  SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM: 4,
  SDL_GPU_TEXTUREFORMAT_R16_UNORM: 5,
  SDL_GPU_TEXTUREFORMAT_R16G16_UNORM: 6,
  SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM: 7,
  SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM: 8,
  SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM: 9,
  SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM: 10,
  SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM: 11,
  SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM: 12,
  /* Compressed Unsigned Normalized Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM: 13,
  SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM: 14,
  SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM: 15,
  SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM: 16,
  SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM: 17,
  SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM: 18,
  /* Compressed Signed Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT: 19,
  /* Compressed Unsigned Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT: 20,
  /* Signed Normalized Float Color Formats  */
  SDL_GPU_TEXTUREFORMAT_R8_SNORM: 21,
  SDL_GPU_TEXTUREFORMAT_R8G8_SNORM: 22,
  SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM: 23,
  SDL_GPU_TEXTUREFORMAT_R16_SNORM: 24,
  SDL_GPU_TEXTUREFORMAT_R16G16_SNORM: 25,
  SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM: 26,
  /* Signed Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_R16_FLOAT: 27,
  SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT: 28,
  SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT: 29,
  SDL_GPU_TEXTUREFORMAT_R32_FLOAT: 30,
  SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT: 31,
  SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT: 32,
  /* Unsigned Float Color Formats */
  SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT: 33,
  /* Unsigned Integer Color Formats */
  SDL_GPU_TEXTUREFORMAT_R8_UINT: 34,
  SDL_GPU_TEXTUREFORMAT_R8G8_UINT: 35,
  SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT: 36,
  SDL_GPU_TEXTUREFORMAT_R16_UINT: 37,
  SDL_GPU_TEXTUREFORMAT_R16G16_UINT: 38,
  SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT: 39,
  SDL_GPU_TEXTUREFORMAT_R32_UINT: 40,
  SDL_GPU_TEXTUREFORMAT_R32G32_UINT: 41,
  SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT: 42,
  /* Signed Integer Color Formats */
  SDL_GPU_TEXTUREFORMAT_R8_INT: 43,
  SDL_GPU_TEXTUREFORMAT_R8G8_INT: 44,
  SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT: 45,
  SDL_GPU_TEXTUREFORMAT_R16_INT: 46,
  SDL_GPU_TEXTUREFORMAT_R16G16_INT: 47,
  SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT: 48,
  SDL_GPU_TEXTUREFORMAT_R32_INT: 49,
  SDL_GPU_TEXTUREFORMAT_R32G32_INT: 50,
  SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT: 51,
  /* SRGB Unsigned Normalized Color Formats */
  SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB: 52,
  SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB: 53,
  /* Compressed SRGB Unsigned Normalized Color Formats */
  SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB: 54,
  SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB: 55,
  SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB: 56,
  SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB: 57,
  /* Depth Formats */
  SDL_GPU_TEXTUREFORMAT_D16_UNORM: 58,
  SDL_GPU_TEXTUREFORMAT_D24_UNORM: 59,
  SDL_GPU_TEXTUREFORMAT_D32_FLOAT: 60,
  SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT: 61,
  SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT: 62,
  /* Compressed ASTC Normalized Float Color Formats*/
  SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM: 63,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM: 64,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM: 65,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM: 66,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM: 67,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM: 68,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM: 69,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM: 70,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM: 71,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM: 72,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM: 73,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM: 74,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM: 75,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM: 76,
  /* Compressed SRGB ASTC Normalized Float Color Formats*/
  SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB: 77,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB: 78,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB: 79,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB: 80,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB: 81,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB: 82,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB: 83,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB: 84,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB: 85,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB: 86,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB: 87,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB: 88,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB: 89,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB: 90,
  /* Compressed ASTC Signed Float Color Formats*/
  SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT: 91,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT: 92,
  SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT: 93,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT: 94,
  SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT: 95,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT: 96,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT: 97,
  SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT: 98,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT: 99,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT: 100,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT: 101,
  SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT: 102,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT: 103,
  SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT: 104,
} as const;

export type GPUTextureFormat =
  (typeof GPUTextureFormat)[keyof typeof GPUTextureFormat];

export const GPUTextureType = {
  SDL_GPU_TEXTURETYPE_2D: 0 /**< The texture is a 2-dimensional image. */,
  SDL_GPU_TEXTURETYPE_2D_ARRAY: 1 /**< The texture is a 2-dimensional array image. */,
  SDL_GPU_TEXTURETYPE_3D: 2 /**< The texture is a 3-dimensional image. */,
  SDL_GPU_TEXTURETYPE_CUBE: 3 /**< The texture is a cube image. */,
  SDL_GPU_TEXTURETYPE_CUBE_ARRAY: 4 /**< The texture is a cube array image. */,
} as const;

export type GPUTextureType =
  (typeof GPUTextureType)[keyof typeof GPUTextureType];

export const GPUTextureUsageFlags = {
  SDL_GPU_TEXTUREUSAGE_SAMPLER:
    (1 << 0) >>> 0 /**< Texture supports sampling. */,
  SDL_GPU_TEXTUREUSAGE_COLOR_TARGET:
    (1 << 1) >>> 0 /**< Texture is a color render target. */,
  SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET:
    (1 << 2) >>> 0 /**< Texture is a depth stencil target. */,
  SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ:
    (1 << 3) >>> 0 /**< Texture supports storage reads in graphics stages. */,
  SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ:
    (1 << 4) >>> 0 /**< Texture supports storage reads in the compute stage. */,
  SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE:
    (1 << 5) >>>
    0 /**< Texture supports storage writes in the compute stage. */,
  SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE:
    (1 << 6) >>>
    0 /**< Texture supports reads and writes in the same compute shader. This is NOT equivalent to READ | WRITE. */,
} as const;

export type GPUTextureUsageFlags =
  (typeof GPUTextureUsageFlags)[keyof typeof GPUTextureUsageFlags];
