export const EventAction = {
  SDL_ADDEVENT: 0,
  SDL_PEEKEVENT: 1,
  SDL_GETEVENT: 2,
} as const;

export type EventAction = (typeof EventAction)[keyof typeof EventAction];

export const EventType = {
  SDL_FIRST: 0,

  /* Application events */
  SDL_QUIT: 0x100,
  SDL_TERMINATING: 0x101,
  SDL_LOW_MEMORY: 0x102,
  SDL_WILL_ENTER_BACKGROUND: 0x103,
  SDL_DID_ENTER_BACKGROUND: 0x104,
  SDL_WILL_ENTER_FOREGROUND: 0x105,
  SDL_DID_ENTER_FOREGROUND: 0x106,
  SDL_LOCALE_CHANGED: 0x107,
  SDL_SYSTEM_THEME_CHANGED: 0x108,

  /* Display events */
  SDL_DISPLAY_ORIENTATION: 0x151,
  SDL_DISPLAY_ADDED: 0x152,
  SDL_DISPLAY_REMOVED: 0x153,
  SDL_DISPLAY_MOVED: 0x154,
  SDL_DISPLAY_DESKTOP_MODE_CHANGED: 0x155,
  SDL_DISPLAY_CURRENT_MODE_CHANGED: 0x156,
  SDL_DISPLAY_CONTENT_SCALE_CHANGED: 0x157,
  SDL_DISPLAY_USABLE_BOUNDS_CHANGED: 0x158,

  /* Window events */
  SDL_WINDOW_SHOWN: 0x202,
  SDL_WINDOW_HIDDEN: 0x203,
  SDL_WINDOW_EXPOSED: 0x204,
  SDL_WINDOW_MOVED: 0x205,
  SDL_WINDOW_RESIZED: 0x206,
  SDL_WINDOW_PIXEL_SIZE_CHANGED: 0x207,
  SDL_WINDOW_METAL_VIEW_RESIZED: 0x208,
  SDL_WINDOW_MINIMIZED: 0x209,
  SDL_WINDOW_MAXIMIZED: 0x20a,
  SDL_WINDOW_RESTORED: 0x20b,
  SDL_WINDOW_MOUSE_ENTER: 0x20c,
  SDL_WINDOW_MOUSE_LEAVE: 0x20d,
  SDL_WINDOW_FOCUS_GAINED: 0x20e,
  SDL_WINDOW_FOCUS_LOST: 0x20f,
  SDL_WINDOW_CLOSE_REQUESTED: 0x210,
  SDL_WINDOW_HIT_TEST: 0x211,
  SDL_WINDOW_ICCPROF_CHANGED: 0x212,
  SDL_WINDOW_DISPLAY_CHANGED: 0x213,
  SDL_WINDOW_DISPLAY_SCALE_CHANGED: 0x214,
  SDL_WINDOW_SAFE_AREA_CHANGED: 0x215,
  SDL_WINDOW_OCCLUDED: 0x216,
  SDL_WINDOW_ENTER_FULLSCREEN: 0x217,
  SDL_WINDOW_LEAVE_FULLSCREEN: 0x218,
  SDL_WINDOW_DESTROYED: 0x219,
  SDL_WINDOW_HDR_STATE_CHANGED: 0x21a,

  /* Keyboard events */
  SDL_KEY_DOWN: 0x300,
  SDL_KEY_UP: 0x301,
  SDL_TEXT_EDITING: 0x302,
  SDL_TEXT_INPUT: 0x303,
  SDL_KEYMAP_CHANGED: 0x304,
  SDL_KEYBOARD_ADDED: 0x305,
  SDL_KEYBOARD_REMOVED: 0x306,
  SDL_TEXT_EDITING_CANDIDATES: 0x307,
  SDL_SCREEN_KEYBOARD_SHOWN: 0x308,
  SDL_SCREEN_KEYBOARD_HIDDEN: 0x309,

  /* Mouse events */
  SDL_MOUSE_MOTION: 0x400,
  SDL_MOUSE_BUTTON_DOWN: 0x401,
  SDL_MOUSE_BUTTON_UP: 0x402,
  SDL_MOUSE_WHEEL: 0x403,
  SDL_MOUSE_ADDED: 0x404,
  SDL_MOUSE_REMOVED: 0x405,

  /* Joystick events */
  SDL_JOYSTICK_AXIS_MOTION: 0x600,
  SDL_JOYSTICK_BALL_MOTION: 0x601,
  SDL_JOYSTICK_HAT_MOTION: 0x602,
  SDL_JOYSTICK_BUTTON_DOWN: 0x603,
  SDL_JOYSTICK_BUTTON_UP: 0x604,
  SDL_JOYSTICK_ADDED: 0x605,
  SDL_JOYSTICK_REMOVED: 0x606,
  SDL_JOYSTICK_BATTERY_UPDATED: 0x607,
  SDL_JOYSTICK_UPDATE_COMPLETE: 0x608,

  /* Gamepad events */
  SDL_GAMEPAD_AXIS_MOTION: 0x650,
  SDL_GAMEPAD_BUTTON_DOWN: 0x651,
  SDL_GAMEPAD_BUTTON_UP: 0x652,
  SDL_GAMEPAD_ADDED: 0x653,
  SDL_GAMEPAD_REMOVED: 0x654,
  SDL_GAMEPAD_REMAPPED: 0x655,
  SDL_GAMEPAD_TOUCHPAD_DOWN: 0x656,
  SDL_GAMEPAD_TOUCHPAD_MOTION: 0x657,
  SDL_GAMEPAD_TOUCHPAD_UP: 0x658,
  SDL_GAMEPAD_SENSOR_UPDATE: 0x659,
  SDL_GAMEPAD_UPDATE_COMPLETE: 0x65a,
  SDL_GAMEPAD_STEAM_HANDLE_UPDATED: 0x65b,

  /* Touch events */
  SDL_FINGER_DOWN: 0x700,
  SDL_FINGER_UP: 0x701,
  SDL_FINGER_MOTION: 0x702,
  SDL_FINGER_CANCELED: 0x703,

  /* Pinch events */
  SDL_PINCH_BEGIN: 0x710,
  SDL_PINCH_UPDATE: 0x711,
  SDL_PINCH_END: 0x712,

  /* Clipboard events */
  SDL_CLIPBOARD_UPDATE: 0x900,

  /* Drag and drop events */
  SDL_DROP_FILE: 0x1000,
  SDL_DROP_TEXT: 0x1001,
  SDL_DROP_BEGIN: 0x1002,
  SDL_DROP_COMPLETE: 0x1003,
  SDL_DROP_POSITION: 0x1004,

  /* Audio hotplug events */
  SDL_AUDIO_DEVICE_ADDED: 0x1100,
  SDL_AUDIO_DEVICE_REMOVED: 0x1101,
  SDL_AUDIO_DEVICE_FORMAT_CHANGED: 0x1102,

  /* Sensor events */
  SDL_SENSOR_UPDATE: 0x1200,

  /* Pen events */
  SDL_PEN_PROXIMITY_IN: 0x1300,
  SDL_PEN_PROXIMITY_OUT: 0x1301,
  SDL_PEN_DOWN: 0x1302,
  SDL_PEN_UP: 0x1303,
  SDL_PEN_BUTTON_DOWN: 0x1304,
  SDL_PEN_BUTTON_UP: 0x1305,
  SDL_PEN_MOTION: 0x1306,
  SDL_PEN_AXIS: 0x1307,

  /* Camera events */
  SDL_CAMERA_DEVICE_ADDED: 0x1400,
  SDL_CAMERA_DEVICE_REMOVED: 0x1401,
  SDL_CAMERA_DEVICE_APPROVED: 0x1402,
  SDL_CAMERA_DEVICE_DENIED: 0x1403,

  /* Render events */
  SDL_RENDER_TARGETS_RESET: 0x2000,
  SDL_RENDER_DEVICE_RESET: 0x2001,
  SDL_RENDER_DEVICE_LOST: 0x2002,

  /* Internal/User */
  SDL_POLL_SENTINEL: 0x7f00,
  SDL_USER: 0x8000,
  SDL_LAST: 0xffff,
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];

export const MouseWheelDirection = {
  SDL_MOUSEWHEEL_NORMAL: 0,
  SDL_MOUSEWHEEL_FLIPPED: 1,
} as const;

export type MouseWheelDirection =
  (typeof MouseWheelDirection)[keyof typeof MouseWheelDirection];

export const JoyHatPosition = {
  SDL_HAT_CENTERED: 0x00,
  SDL_HAT_UP: 0x01,
  SDL_HAT_RIGHT: 0x02,
  SDL_HAT_DOWN: 0x04,
  SDL_HAT_LEFT: 0x08,
  SDL_HAT_RIGHTUP: 0x02 | 0x01, // 0x03
  SDL_HAT_RIGHTDOWN: 0x02 | 0x04, // 0x06
  SDL_HAT_LEFTUP: 0x08 | 0x01, // 0x09
  SDL_HAT_LEFTDOWN: 0x08 | 0x04, // 0x0C
} as const;

export type JoyHatPosition =
  (typeof JoyHatPosition)[keyof typeof JoyHatPosition];

export const PenInputFlags = {
  SDL_PEN_INPUT_DOWN: (1 << 0) >>> 0,
  SDL_PEN_INPUT_BUTTON_1: (1 << 1) >>> 0,
  SDL_PEN_INPUT_BUTTON_2: (1 << 2) >>> 0,
  SDL_PEN_INPUT_BUTTON_3: (1 << 3) >>> 0,
  SDL_PEN_INPUT_BUTTON_4: (1 << 4) >>> 0,
  SDL_PEN_INPUT_BUTTON_5: (1 << 5) >>> 0,
  SDL_PEN_INPUT_ERASER_TIP: (1 << 30) >>> 0,
  SDL_PEN_INPUT_IN_PROXIMITY: (1 << 31) >>> 0,
} as const;

export type PenInputFlags = (typeof PenInputFlags)[keyof typeof PenInputFlags];

export const PenAxis = {
  SDL_PEN_AXIS_PRESSURE: 0 /**< Pen pressure.  Unidirectional: 0 to 1.0 */,
  SDL_PEN_AXIS_XTILT: 1 /**< Pen horizontal tilt angle.  Bidirectional: -90.0 to 90.0 (left-to-right). */,
  SDL_PEN_AXIS_YTILT: 2 /**< Pen vertical tilt angle.  Bidirectional: -90.0 to 90.0 (top-to-down). */,
  SDL_PEN_AXIS_DISTANCE: 3 /**< Pen distance to drawing surface.  Unidirectional: 0.0 to 1.0 */,
  SDL_PEN_AXIS_ROTATION: 4 /**< Pen barrel rotation.  Bidirectional: -180 to 179.9 (clockwise, 0 is facing up, -180.0 is facing down). */,
  SDL_PEN_AXIS_SLIDER: 5 /**< Pen finger wheel or slider (e.g., Airbrush Pen).  Unidirectional: 0 to 1.0 */,
  SDL_PEN_AXIS_TANGENTIAL_PRESSURE: 6 /**< Pressure from squeezing the pen ("barrel pressure"). */,
  SDL_PEN_AXIS_COUNT: 7 /**< Total known pen axis types in this version of SDL. This number may grow in future releases! */,
} as const;

export type PenAxis = (typeof PenAxis)[keyof typeof PenAxis];
